"""edit users table

Revision ID: d9fc4b2a8364
Revises: 81fd6c2e18ce
Create Date: 2025-08-21 13:24:15.898576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fc4b2a8364'
down_revision: Union[str, Sequence[str], None] = '81fd6c2e18ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_updated_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated_message')
    # ### end Alembic commands ###
